# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Drive\SBE3\2021 2nd Semester\DSP\Tasks\Task4\Shazam-like-app\dist\app\UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1010, 778)
        mainWindow.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(47, 47, 77);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 2, 3, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setObjectName("searchButton")
        self.gridLayout_2.addWidget(self.searchButton, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.resultsTable = QtWidgets.QTableWidget(self.centralwidget)
        self.resultsTable.setEnabled(True)
        self.resultsTable.setStyleSheet("")
        self.resultsTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.resultsTable.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.resultsTable.setAlternatingRowColors(False)
        self.resultsTable.setObjectName("resultsTable")
        self.resultsTable.setColumnCount(0)
        self.resultsTable.setRowCount(0)
        self.gridLayout_2.addWidget(self.resultsTable, 1, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 0, 3, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 3, 0, 1, 4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 2, 3, 1, 1)
        self.mixing_slider = QtWidgets.QSlider(self.centralwidget)
        self.mixing_slider.setMaximum(100)
        self.mixing_slider.setSingleStep(10)
        self.mixing_slider.setPageStep(10)
        self.mixing_slider.setProperty("value", 50)
        self.mixing_slider.setOrientation(QtCore.Qt.Horizontal)
        self.mixing_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.mixing_slider.setObjectName("mixing_slider")
        self.gridLayout_3.addWidget(self.mixing_slider, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 0, 1, 4)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.label_4.setMidLineWidth(2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.song1 = QtWidgets.QLabel(self.centralwidget)
        self.song1.setStyleSheet("background-color: rgb(74, 74, 110);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.song1.setObjectName("song1")
        self.gridLayout_3.addWidget(self.song1, 1, 0, 1, 1)
        self.song2 = QtWidgets.QLabel(self.centralwidget)
        self.song2.setStyleSheet("background-color: rgb(74, 74, 110);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.song2.setObjectName("song2")
        self.gridLayout_3.addWidget(self.song2, 1, 2, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 2, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1010, 22))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setStyleSheet("selection-background-color: rgb(35, 35, 50);\n"
"gridline-color: rgb(255, 255, 255);")
        self.menufile.setObjectName("menufile")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.Browse_songs = QtWidgets.QAction(mainWindow)
        self.Browse_songs.setObjectName("Browse_songs")
        self.actionClear = QtWidgets.QAction(mainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionNew_tab = QtWidgets.QAction(mainWindow)
        self.actionNew_tab.setObjectName("actionNew_tab")
        self.New_window = QtWidgets.QAction(mainWindow)
        self.New_window.setObjectName("New_window")
        self.menufile.addAction(self.New_window)
        self.menufile.addAction(self.Browse_songs)
        self.menufile.addAction(self.actionClear)
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(mainWindow)
        self.mixing_slider.valueChanged['int'].connect(self.label_4.setNum)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Music Discovery"))
        self.searchButton.setText(_translate("mainWindow", "Search"))
        self.label_3.setText(_translate("mainWindow", " Similar songs"))
        self.label_4.setToolTip(_translate("mainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\"><br/></span></p></body></html>"))
        self.label_4.setWhatsThis(_translate("mainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_4.setText(_translate("mainWindow", "50"))
        self.song1.setText(_translate("mainWindow", " Song 1"))
        self.song2.setText(_translate("mainWindow", " Song 2"))
        self.menufile.setTitle(_translate("mainWindow", "File"))
        self.Browse_songs.setText(_translate("mainWindow", "Browse songs"))
        self.Browse_songs.setShortcut(_translate("mainWindow", "Ctrl+B"))
        self.actionClear.setText(_translate("mainWindow", "Clear"))
        self.actionClear.setShortcut(_translate("mainWindow", "Ctrl+C"))
        self.actionNew_tab.setText(_translate("mainWindow", "New tab"))
        self.New_window.setText(_translate("mainWindow", "New window"))
        self.New_window.setShortcut(_translate("mainWindow", "Ctrl+N"))
